name: attendancesystem_flutter
description: A Deep Learning Based Mobile Application for Attendance System.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
  
    sdk: flutter

  #State Management
  mobx: ^2.0.7+5
  provider: ^6.0.1
  flutter_mobx: ^2.0.6+1

  #Network
  http: ^0.13.4
  dio: ^5.0.3
  vexana: ^3.4.1

  #Core
  intl: ^0.17.0
  webview_flutter: ^2.1.2
  kartal: ^2.3.2
  path_provider: ^2.0.8
  
  #Database
  shared_preferences: ^2.0.8
  flutter_dotenv: ^5.0.2

  #Language
  easy_localization: ^3.0.1

  #Google
  json_annotation: ^4.3.0

  #UI Utilities
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.2.0
  auto_size_text: ^3.0.0
  image_picker: ^0.8.4+4
  image_pickers: ^2.0.0+2
  cached_network_image: ^3.2.0
  full_screen_image: any
  flutter_svg: ^0.23.0+1
  lottie: ^2.3.0
  pin_code_fields: ^7.3.0
  timer_count_down: ^2.2.0
  share_plus: ^4.0.10
  http_parser: ^4.0.0  


dev_dependencies:
  flutter_lints: ^2.0.1
  mockito: ^5.0.16
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7
  json_serializable: ^6.0.1


  flutter_launcher_icons: ^0.9.2

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "asset/image/attendancesystem_icon.png"

flutter:
  uses-material-design: true
  assets:
    # - asset/app/.env
    - asset/image/
    - asset/lang/
    - asset/svg/
    - asset/lottie/

  fonts:
    - family: Montserrat
      fonts:
        - asset: asset/fonts/Montserrat-Black.ttf
        - asset: asset/fonts/Montserrat-BlackItalic.ttf
        - asset: asset/fonts/Montserrat-Bold.ttf
        - asset: asset/fonts/Montserrat-BoldItalic.ttf
        - asset: asset/fonts/Montserrat-ExtraBold.ttf
        - asset: asset/fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: asset/fonts/Montserrat-ExtraLight.ttf
        - asset: asset/fonts/Montserrat-ExtraLightItalic.ttf
        - asset: asset/fonts/Montserrat-Italic.ttf
        - asset: asset/fonts/Montserrat-Light.ttf
        - asset: asset/fonts/Montserrat-LightItalic.ttf
        - asset: asset/fonts/Montserrat-Medium.ttf
        - asset: asset/fonts/Montserrat-MediumItalic.ttf
        - asset: asset/fonts/Montserrat-Regular.ttf
        - asset: asset/fonts/Montserrat-SemiBold.ttf
        - asset: asset/fonts/Montserrat-SemiBoldItalic.ttf
        - asset: asset/fonts/Montserrat-Thin.ttf
        - asset: asset/fonts/Montserrat-ThinItalic.ttf